name: Update Codeforces Stats

on:
  schedule:
    - cron: '0 * * * *'  # This runs the action every hour
  workflow_dispatch:  # Allows you to trigger the action manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Codeforces Stats
        run: |
          CODEFORCES_USERNAME="esllam"
          SOLVED_COUNT=$(curl -s "https://codeforces.com/api/user.status?handle=$CODEFORCES_USERNAME&from=1" | jq -r '[.result[] | select(.verdict == "OK")] | unique_by(.problem.name) | length')
          echo "Solved problems: $SOLVED_COUNT"
          echo "SOLVED_COUNT=$SOLVED_COUNT" >> $GITHUB_ENV
      
      - name: Update README
        run: |
          sed -i "s|Codeforces problems solved: [0-9]*|Codeforces problems solved: $SOLVED_COUNT|" README.md

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update Codeforces problem count" || echo "No changes to commit"
          git push
